config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :challengers
  resources :challenges
  resources :posts
  resources :welcome

  root 'welcome#index'

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	belongs_to :challenger
	has_many :posts
	validates :title, presence: true

	scope :ending_soon, -> {where('end_date > ? AND end_date  < ? ' , Date.today , 3.days.from_now)}

	def self.ending_soon
		where('end_date > ? AND end_date  < ? ' , Date.today , 3.days.from_now)
	end

	# #validations
	# 	validates :challenger_id
	#   validates :title, presence :true
 #    validates :description, presence :true
 #    validates :start_date, presence true
 #    validates :end_date, presence true
 #    validates :challenger_id, presence true
end

app/models/challenger.rb
class Challenger < ActiveRecord::Base
	has_many :challenges
	has_many :posts
	has_many :relationships
	accepts_nested_attributes_for :challenges
	# #validations
	# validates_associated :challenges
	# validates_associated :posts
	# validates_associated :relationships
	# validates :username, presence :true
	# validates :username, uniqueness :true
 #  validates :password, presence :true
 #  validates :password, uniqueness :true
 #  validates :email, presence :true
 #  validates :email, uniqueness :true
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :challenger

	#validations
    # validates :description, presence :true
end

app/models/relationships.rb
class Relationships < ActiveRecord::Base
	belongs_to :user
	belongs_to :challenger

	#validations
    validates :user_id, presence :true
    validates :challenger_id, presence :true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :relationships
	
	

	def self.todays_date
		where('created_at > ?' , Date.today)
	end
	

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/challengers_controller.rb
class ChallengersController < ApplicationController
	def index
			@challengers = Challenger.all
		end

		def new
			@new_challenger = Challenger.new
			@new_challenger.challenges.build
		end

		def create
			@new_challenger = Challenger.new(challenger_params)
			if @new_challenger.save
				
				redirect_to challengers_path
			else
				redirect_to new_challenger_path
			end
		end

		def show
			@challenger = Challenger.find(params[:id])
			@post_id = @challenger.id
			@posts = Post.where('challenger_id = ?' , @post_id)
		end

		def edit
			@challenger = Challenger.find(params[:id])
		end

		def update
			@challenger =Challenger.find(params[:id])
			if @challenger.update_attributes(challenger_params)
				redirect_to challengers_path
			else
				redirect_to edit_challengers_path
			end
		end

		def destroy
			@challenger =Challenger.find(params[:id])
			@challenger.delete
				redirect_to challengers_path
		end

	private

		def challenger_params
			params.require(:challenger).permit(:username, :password, :name, :email, :interests,  challenges_attributes: [:title, :description, :start_date, :end_date, :interests])
		
		end


	end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  


  def index
    @challenges = Challenge.all
  end


  def show
    @challenge = Challenge.find(params[:id])
  end

  
  def new
    @new_challenge = Challenge.new
  end

  
  def edit
    @challenge = Challenge.find(params[:id])
  end

  
  def create
    @new_challenge = Challenge.new(challenge_params)
    if @new_challenge.save
        redirect_to challenges_path
      else
        redirect_to new_challenge_path
      end

    
  end

  def update
    @challenge =Challenge.find(params[:id])
      if @challenge.update_attributes(challenge_params)
        redirect_to challenges_path
      else
        redirect_to edit_challenges_path
      end
  end


  def destroy
    @challenge =Challenge.find(params[:id])
    @challenge.destroy
    redirect_to challenges_path
   
    
  end

  private
   

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params[:challenge].permit!
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  


  def index
    @posts = Post.all
  end


  def show
    @post = Post.find(params[:id])
  end

  
  def new
    @new_post = Post.new
  end

  
  def edit
    @post = Post.find(params[:id])
  end

  
  def create
    @new_post = Post.new(post_params)
    if @new_post.save
        redirect_to posts_path
      else
        redirect_to new_post_path
      end
	end

  def update
    @post =Post.find(params[:id])
      if @post.update_attributes(post_params)
        redirect_to posts_path
      else
        redirect_to edit_posts_path
      end
  end


  def destroy
    @post =Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
   
    
  end

  private
   

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params[:post].permit!
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@new_user = User.new
	end

	def create
		@new_user = User.new(user_params)
		if @new_user.save
			redirect_to users_path
		else
			redirect_to new_user_path
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user =User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to users_path
		else
			redirect_to edit_users_path
		end
	end

	def destroy
		@user =User.find(params[:id])
		@user.delete
			redirect_to users_path
	end

private

	def user_params
		params.require(:user).permit!
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@todays_users = User.todays_date
		@challenge = Challenge.ending_soon
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def formatted_date(date)
		date.strftime("%B %-d, %Y")
	end
end

app/helpers/challengers_helper.rb
module ChallengersHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/challengers/_challenger.html.haml
= f.label :username
%br
= f.text_field :username
%br
= f.label :password
%br
= f.text_field :password
%br
= f.label :name
%br
= f.text_field :name
%br
= f.label :email
%br
=	f.text_field :email
%br
= f.label :interests
%br
= f.text_field :interests
%br

app/views/challengers/edit.html.haml
= render "layouts/header"
= form_for @challenger, url: challenger_path do |f|
	= render "challenger", f: f
	= f.submit

app/views/challengers/index.html.haml
= render "layouts/header"
.row
	.text-center
		%h1 Challengers
		= link_to "Add a new Challenger" , new_challenger_path , method: "get"
- @challengers.each do |c|
	.col-sm-6.col-md-4.panel.panel-primary.text-center
		%h1
			= link_to "#{c.username}" , challenger_path(c) , method: "get"  
		%br
		Real Name:
		= c.name
		%br
		Email:
		= c.email
		%br
		Interests:
		= c.interests
		%br

app/views/challengers/new.html.haml
= render "layouts/header"
= form_for @new_challenger, url: challengers_path do |f|
	.container
		
		.col-sm-6.col-md-6.col-lg-6
			%h1 create a challenger
			= render "challenger", f: f
		
		.col-sm-6.col-md-6.col-lg-6
			%h2 add a challenge!
			=f.fields_for :challenges do|ff| 
				title
				%br
				= ff.text_field :title
				%br
				description
				%br
				= ff.text_field :description
				%br
				interests
				%br
				= ff.text_field :interests
				%br
				start date
				%br
				= ff.date_field :start_date
				%br
				end date
				%br
				= ff.date_field :end_date
				%br
				
			= f.submit

app/views/challengers/show.html.haml
= render "layouts/header"

.row
	.text-center
		%h1
			= @challenger.name


		.btn-group
			= link_to "Edit" , edit_challenger_path , method: "get" , :class => "btn btn-warning" , :role => "button" 
			= link_to "Delete" , challenger_path , method: "delete" , :class => "btn btn-danger" , :role => "button" 
			= mail_to "#{@challenger.email}" , "Email" , method: "get" , :class => "btn btn-info" , :role => "button" 

		%br
		%h1 posts
		= button_to "add new post" , new_post_path, method: "get" , :class => "btn btn-default"
		%br
.container
	%div.container{ :style => "border-left: 1px solid #eee;" }
	- @posts.each do |p|


		%h1
			=p.title
		
		%h3
			
			=p.description
		=link_to "delete this post" , post_path(p) , method: "delete"
		=link_to "edit this post" , edit_post_path(p) , method: "get"
		%hr

			

app/views/challenges/_challenge.html.haml
= f.label :title
= f.text_field :title
%br
= f.label :description
= f.text_field :description
%br
= f.label :start_date
= f.date_field :start_date
%br
= f.label :end_date
= f.date_field :end_date
%br
= f.label :interests
= f.text_field :interests
%br
Challenger:
= f.select :challenger_id, Challenger.all.collect {|c| [c.name, c.id]} 



= f.submit

app/views/challenges/edit.html.haml
= render "layouts/header"
= form_for @challenge, url: challenge_path do |f|
	= render "challenge", f: f

app/views/challenges/index.html.haml
= render "layouts/header"
.row
	.text-center
		%h1 Challengers
		= link_to "Add a new Challenge" , new_challenge_path , method: "get"
- @challenges.each do |c|
	.col-sm-6.col-md-4.panel.panel-primary.text-center
		%h1
			= link_to "#{c.title}" , challenge_path(c) , method: "get" 
		%br
		description:
		= c.description
		%br
		start date:
		= formatted_date(c.start_date)
		%br
		end date:
		= formatted_date(c.end_date)
		%br
		interests:
		= c.interests
		%br
		challenger
		- if c.challenger
			= c.challenger.name

		%br
		%br

app/views/challenges/new.html.haml
= render "layouts/header"
= form_for @new_challenge, url: challenges_path do |f|
	= render "challenge", f: f

app/views/challenges/show.html.haml
= render "layouts/header"
%h1 Challenge
= @challenge.title


=link_to "delete this challenge" , challenge_path , method: "delete"
=link_to "edit this challenge" , edit_challenge_path , method: "get"


%h2 Challenger
= @challenge.challenger.name

app/views/layouts/_header.html.haml
.nav-bar.navbar-default.text-center.navbar-static-top
	%h1 
		= link_to "Frank" , root_path , method: "get" 
	%br
	.btn-group
		= link_to "User" , users_path , method: "get" , :class => "btn btn-default" , :role => "button" 
		= link_to "Challengers" , challengers_path , method: "get" , :class => "btn btn-default" , :role => "button" 
		= link_to "Challenges" , challenges_path , method: "get" , :class => "btn btn-default" , :role => "button"
		= link_to "Post" , posts_path , method: "get" , :class => "btn btn-default" , :role => "button"  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/posts/_post.html.haml
= f.label :title
= f.text_field :title
%br
= f.label :description
= f.text_area :description
%br
challenger name
= f.select :challenger_id, Challenger.all.collect {|c| [c.name, c.id]} 

%br
select User
= f.select :user_id, User.all.collect {|u| [u.name, u.id]} 
%br

= f.submit

app/views/posts/edit.html.haml
= render "layouts/header"
= form_for @post, url: post_path do |f|
	= render "post", f: f

app/views/posts/index.html.haml
= render "layouts/header"
%div.container{ :style => "border-left: 1px solid #eee;" }
	- @posts.each do |p|
	
	
		%h1
			=p.title
		
		%h3
			
			=p.description
		=link_to "delete this post" , post_path(p) , method: "delete"
		=link_to "edit this post" , edit_post_path(p) , method: "get"
		%hr
		

app/views/posts/new.html.haml
= render "layouts/header"
= form_for @new_post, url: posts_path do |f|
	= render "post", f: f

app/views/posts/show.html.haml
= render "layouts/header"
= @post.title
%br
= @post.description

%br

=link_to "delete this post" , post_path , method: "delete"
%br
=link_to "edit this post" , edit_post_path , method: "get"

app/views/users/_user.html.haml
= f.label :username
%br
= f.text_field :username
%br
= f.label :password
%br
= f.text_field :password
%br
= f.label :name
%br
= f.text_field :name
%br
= f.label :email
%br
=	f.text_field :email
%br
= f.label :interests
%br
= f.text_field :interests
%br
= f.label :description
%br
= f.text_field :description
%br

= f.submit

app/views/users/edit.html.haml
= render "layouts/header"
.container.text-center
	%br
	= form_for @user, url: user_path do |f|
		= render "user", f: f


	

app/views/users/index.html.haml
= render "layouts/header"

.row
	.text-center
		%h1 Users
		= link_to "Add a new User" , new_user_path , method: "get"
	- @users.each do |u|
		
		.col-sm-6.col-md-4.panel.panel-primary.text-center

			%br
			%h1
				= link_to "#{u.username}" , user_path(u) , method: "get"  
				 
			%br
			Real Name:
			= u.name
			%br
			
			Description:
			= u.description
			%br
			%br

app/views/users/new.html.haml
= render "layouts/header"
.container.text-center
	%br
	= form_for @new_user, url: users_path do |f|
		= render "user", f: f

	

	

app/views/users/show.html.haml
= render "layouts/header"
.row
	.text-center
		%br
		%h1 
			= @user.username
		%br
			= @user.name
		%br
			= @user.description
		%br
			= @user.interests
		%br
		.btn-group
			= link_to "Edit" , edit_user_path , method: "get" , :class => "btn btn-warning" , :role => "button" 
			= link_to "Delete" , user_path , method: "delete" , :class => "btn btn-danger" , :role => "button" 
			= mail_to "#{@user.email}" , "Email" , method: "get" , :class => "btn btn-info" , :role => "button" 

app/views/welcome/index.html.haml
= render "layouts/header"

.container
	%h1
		Todays new users
	%br 
	- @todays_users.each do |tu|
		=tu.username
		%br

.container
	%h1
		Challenges ending soon
	%br
	- @challenge.each do |c|
		=link_to "#{c.title}" , challenge_path(c) , method: "get"
		%br